# Generated by Django 5.0.6 on 2026-07-01 18:19

import django.core.validators
import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(help_text='URL friendly string for the category', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, help_text='Icon name or class (e.g. for Lucide icons)', max_length=100, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
                ('parent_category', models.ForeignKey(blank=True, help_text='The parent category if this is a subcategory', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='products.category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalCategory',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(help_text='URL friendly string for the category', max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, help_text='Icon name or class (e.g. for Lucide icons)', max_length=100, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parent_category', models.ForeignKey(blank=True, db_constraint=False, help_text='The parent category if this is a subcategory', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='products.category')),
            ],
            options={
                'verbose_name': 'historical category',
                'verbose_name_plural': 'historical Categories',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HSCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(db_index=True, help_text='Standard HS Code (e.g. 8703.23)', max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^\\d{4}(\\.\\d{2})*$', 'HS Code must be standard numeric format, optionally separated by dots.')])),
                ('description', models.TextField(help_text='Description of the goods covered by this HS code')),
                ('section', models.CharField(blank=True, help_text='HS Section (Roman Numeral or Description)', max_length=255, null=True)),
                ('chapter', models.CharField(blank=True, help_text='HS Chapter (first 2 digits)', max_length=5, null=True)),
                ('heading', models.CharField(blank=True, help_text='HS Heading (first 4 digits)', max_length=10, null=True)),
                ('subheading', models.CharField(blank=True, help_text='HS Subheading (first 6 digits)', max_length=15, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional customs notes for this HS code', null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Deprecated', 'Deprecated')], default='Active', max_length=20)),
                ('effective_from', models.DateField(blank=True, help_text='Date when this HS code becomes effective', null=True)),
                ('effective_to', models.DateField(blank=True, help_text='Date when this HS code expires', null=True)),
                ('version', models.PositiveIntegerField(default=1, help_text='Version number of this HS Code entry')),
                ('parent', models.ForeignKey(blank=True, help_text='Parent HS code if applicable (e.g. Heading for a Subheading)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='products.hscode')),
            ],
            options={
                'verbose_name': 'HS Code',
                'verbose_name_plural': 'HS Codes',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalProduct',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('keywords', models.TextField(blank=True, help_text='Comma separated keywords for better searching', null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
                ('image', models.TextField(blank=True, help_text='Product image placeholder', max_length=100, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('category', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='products.category')),
                ('default_country', models.ForeignKey(blank=True, db_constraint=False, help_text='Default country of origin if applicable', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.country')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('hs_code', models.ForeignKey(blank=True, db_constraint=False, help_text='The classification HS code for this product', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='products.hscode')),
            ],
            options={
                'verbose_name': 'historical product',
                'verbose_name_plural': 'historical products',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalHSCode',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(db_index=True, help_text='Standard HS Code (e.g. 8703.23)', max_length=20, validators=[django.core.validators.RegexValidator('^\\d{4}(\\.\\d{2})*$', 'HS Code must be standard numeric format, optionally separated by dots.')])),
                ('description', models.TextField(help_text='Description of the goods covered by this HS code')),
                ('section', models.CharField(blank=True, help_text='HS Section (Roman Numeral or Description)', max_length=255, null=True)),
                ('chapter', models.CharField(blank=True, help_text='HS Chapter (first 2 digits)', max_length=5, null=True)),
                ('heading', models.CharField(blank=True, help_text='HS Heading (first 4 digits)', max_length=10, null=True)),
                ('subheading', models.CharField(blank=True, help_text='HS Subheading (first 6 digits)', max_length=15, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional customs notes for this HS code', null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Deprecated', 'Deprecated')], default='Active', max_length=20)),
                ('effective_from', models.DateField(blank=True, help_text='Date when this HS code becomes effective', null=True)),
                ('effective_to', models.DateField(blank=True, help_text='Date when this HS code expires', null=True)),
                ('version', models.PositiveIntegerField(default=1, help_text='Version number of this HS Code entry')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, db_constraint=False, help_text='Parent HS code if applicable (e.g. Heading for a Subheading)', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='products.hscode')),
            ],
            options={
                'verbose_name': 'historical HS Code',
                'verbose_name_plural': 'historical HS Codes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('keywords', models.TextField(blank=True, help_text='Comma separated keywords for better searching', null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
                ('image', models.ImageField(blank=True, help_text='Product image placeholder', null=True, upload_to='products/')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category')),
                ('default_country', models.ForeignKey(blank=True, help_text='Default country of origin if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_products', to='core.country')),
                ('hs_code', models.ForeignKey(help_text='The classification HS code for this product', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.hscode')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
