# Generated by Django 5.0.6 on 2026-07-01 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='alternative_names',
            field=models.TextField(blank=True, help_text='Comma separated alternative or colloquial names', null=True),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='brand_names',
            field=models.TextField(blank=True, help_text='Comma separated brand names', null=True),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='popularity_score',
            field=models.IntegerField(default=0, help_text='Number of times this product was searched/calculated'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='search_weight',
            field=models.IntegerField(default=0, help_text='Higher weight products appear first in search'),
        ),
        migrations.AddField(
            model_name='product',
            name='alternative_names',
            field=models.TextField(blank=True, help_text='Comma separated alternative or colloquial names', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='brand_names',
            field=models.TextField(blank=True, help_text='Comma separated brand names', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='popularity_score',
            field=models.IntegerField(default=0, help_text='Number of times this product was searched/calculated'),
        ),
        migrations.AddField(
            model_name='product',
            name='search_weight',
            field=models.IntegerField(default=0, help_text='Higher weight products appear first in search'),
        ),
    ]
