# Generated by Django 5.2.16 on 2026-08-03 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TariffCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Tariff Categories',
            },
        ),
        migrations.CreateModel(
            name='VATRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, help_text='Percentage e.g., 15.00 for 15%', max_digits=5)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, help_text='Leave blank if this is the currently active rate', null=True)),
            ],
            options={
                'verbose_name': 'VAT Rate',
                'verbose_name_plural': 'VAT Rates',
            },
        ),
        migrations.CreateModel(
            name='HSCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=20)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('duty_rate', models.DecimalField(decimal_places=2, help_text='Percentage e.g., 15.00 for 15%', max_digits=5)),
                ('vat_applicable', models.BooleanField(default=True)),
                ('surtax_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('excise_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_duty_free', models.BooleanField(default=False)),
                ('search_aliases', models.CharField(blank=True, help_text='Comma-separated alternative names (e.g., "iPhone, cellphone")', max_length=512)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hs_codes', to='tariffs.tariffcategory')),
            ],
            options={
                'verbose_name_plural': 'HS Codes',
            },
        ),
    ]
