# Generated by Django 5.0.6 on 2026-07-01 18:19

import django.core.validators
import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('customs', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalImportRestriction',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('restriction_type', models.CharField(choices=[('ALLOWED', 'Allowed'), ('RESTRICTED', 'Restricted'), ('PROHIBITED', 'Prohibited')], default='RESTRICTED', max_length=20)),
                ('description', models.TextField(help_text='Detailed explanation of the restriction')),
                ('license_required', models.BooleanField(default=False)),
                ('permit_required', models.BooleanField(default=False)),
                ('inspection_required', models.BooleanField(default=False)),
                ('health_certificate', models.BooleanField(default=False)),
                ('veterinary_certificate', models.BooleanField(default=False)),
                ('plant_permit', models.BooleanField(default=False)),
                ('radiation_clearance', models.BooleanField(default=False)),
                ('dangerous_goods', models.BooleanField(default=False)),
                ('military_goods', models.BooleanField(default=False)),
                ('other_requirements', models.BooleanField(default=False)),
                ('required_documents', models.TextField(blank=True, help_text='Comma separated list of required documents', null=True)),
                ('reference_number', models.CharField(blank=True, help_text='Internal or agency reference number', max_length=100, null=True)),
                ('legal_citation', models.CharField(blank=True, help_text='Legal basis for the restriction', max_length=255, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('government_agency', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='customs.governmentagency')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('hs_code', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='products.hscode')),
            ],
            options={
                'verbose_name': 'historical import restriction',
                'verbose_name_plural': 'historical import restrictions',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ImportRestriction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('restriction_type', models.CharField(choices=[('ALLOWED', 'Allowed'), ('RESTRICTED', 'Restricted'), ('PROHIBITED', 'Prohibited')], default='RESTRICTED', max_length=20)),
                ('description', models.TextField(help_text='Detailed explanation of the restriction')),
                ('license_required', models.BooleanField(default=False)),
                ('permit_required', models.BooleanField(default=False)),
                ('inspection_required', models.BooleanField(default=False)),
                ('health_certificate', models.BooleanField(default=False)),
                ('veterinary_certificate', models.BooleanField(default=False)),
                ('plant_permit', models.BooleanField(default=False)),
                ('radiation_clearance', models.BooleanField(default=False)),
                ('dangerous_goods', models.BooleanField(default=False)),
                ('military_goods', models.BooleanField(default=False)),
                ('other_requirements', models.BooleanField(default=False)),
                ('required_documents', models.TextField(blank=True, help_text='Comma separated list of required documents', null=True)),
                ('reference_number', models.CharField(blank=True, help_text='Internal or agency reference number', max_length=100, null=True)),
                ('legal_citation', models.CharField(blank=True, help_text='Legal basis for the restriction', max_length=255, null=True)),
                ('government_agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restrictions', to='customs.governmentagency')),
                ('hs_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_restrictions', to='products.hscode')),
            ],
            options={
                'ordering': ['hs_code__code'],
            },
        ),
        migrations.CreateModel(
            name='TariffRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('tariff_type', models.CharField(choices=[('IMPORT_DUTY', 'Import Duty'), ('VAT', 'Value Added Tax'), ('EXCISE', 'Excise Duty'), ('SURTAX', 'Surtax'), ('CARBON_TAX', 'Carbon Tax'), ('PROCESSING_FEE', 'Processing Fee'), ('OTHER', 'Other Government Charge')], default='IMPORT_DUTY', max_length=50)),
                ('percentage_rate', models.DecimalField(blank=True, decimal_places=3, help_text='Percentage rate (0-100+)', max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('fixed_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Fixed monetary amount', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('calculation_basis', models.CharField(choices=[('PERCENTAGE', 'Percentage'), ('FOB', 'Free On Board Value'), ('CIF', 'Cost, Insurance, Freight Value'), ('WEIGHT', 'Per Kg/Tonne'), ('VOLUME', 'Per Liter/M3'), ('QUANTITY', 'Per Item/Unit'), ('FLAT_FEE', 'Flat Fee')], default='PERCENTAGE', max_length=50)),
                ('effective_from', models.DateField(help_text='Date when these rates become effective')),
                ('effective_to', models.DateField(blank=True, help_text='Date when these rates expire (leave blank if indefinite)', null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
                ('legal_reference', models.CharField(blank=True, help_text='Statutory Instrument or Legal Citation', max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_current', models.BooleanField(default=True, help_text='Is this the current active version?')),
                ('country', models.ForeignKey(blank=True, help_text='Specific Country of Origin (leave blank if global)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tariff_rates', to='core.country')),
                ('hs_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tariff_rates', to='products.hscode')),
                ('previous_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='tariffs.tariffrate')),
                ('trade_agreement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tariff_rates', to='customs.tradeagreement')),
            ],
            options={
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalTariffRate',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('tariff_type', models.CharField(choices=[('IMPORT_DUTY', 'Import Duty'), ('VAT', 'Value Added Tax'), ('EXCISE', 'Excise Duty'), ('SURTAX', 'Surtax'), ('CARBON_TAX', 'Carbon Tax'), ('PROCESSING_FEE', 'Processing Fee'), ('OTHER', 'Other Government Charge')], default='IMPORT_DUTY', max_length=50)),
                ('percentage_rate', models.DecimalField(blank=True, decimal_places=3, help_text='Percentage rate (0-100+)', max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('fixed_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Fixed monetary amount', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('calculation_basis', models.CharField(choices=[('PERCENTAGE', 'Percentage'), ('FOB', 'Free On Board Value'), ('CIF', 'Cost, Insurance, Freight Value'), ('WEIGHT', 'Per Kg/Tonne'), ('VOLUME', 'Per Liter/M3'), ('QUANTITY', 'Per Item/Unit'), ('FLAT_FEE', 'Flat Fee')], default='PERCENTAGE', max_length=50)),
                ('effective_from', models.DateField(help_text='Date when these rates become effective')),
                ('effective_to', models.DateField(blank=True, help_text='Date when these rates expire (leave blank if indefinite)', null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
                ('legal_reference', models.CharField(blank=True, help_text='Statutory Instrument or Legal Citation', max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_current', models.BooleanField(default=True, help_text='Is this the current active version?')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('country', models.ForeignKey(blank=True, db_constraint=False, help_text='Specific Country of Origin (leave blank if global)', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.country')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('hs_code', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='products.hscode')),
                ('trade_agreement', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='customs.tradeagreement')),
                ('previous_version', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tariffs.tariffrate')),
            ],
            options={
                'verbose_name': 'historical tariff rate',
                'verbose_name_plural': 'historical tariff rates',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddIndex(
            model_name='tariffrate',
            index=models.Index(fields=['hs_code', 'country'], name='tariffs_tar_hs_code_e0cfe7_idx'),
        ),
        migrations.AddIndex(
            model_name='tariffrate',
            index=models.Index(fields=['hs_code', 'tariff_type'], name='tariffs_tar_hs_code_808a60_idx'),
        ),
    ]
