# Generated by Django 5.2.16 on 2026-08-03 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_currency', models.CharField(choices=[('USD', 'US Dollar')], default='USD', max_length=3)),
                ('target_currency', models.CharField(choices=[('ZWG', 'Zimbabwe Gold'), ('ZAR', 'South African Rand'), ('GBP', 'British Pound')], max_length=3)),
                ('rate', models.DecimalField(decimal_places=6, max_digits=12)),
                ('fetched_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['-fetched_at'],
            },
        ),
    ]
