# Generated by Django 5.0.6 on 2026-07-01 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculations', '0001_initial'),
        ('customs', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedcalculation',
            name='duty_exemption',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customs.dutyexemption'),
        ),
        migrations.AddField(
            model_name='savedcalculation',
            name='hs_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calculations', to='products.hscode'),
        ),
        migrations.AddField(
            model_name='savedcalculation',
            name='trade_agreement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customs.tradeagreement'),
        ),
    ]
