# Generated by Django 5.0.6 on 2026-07-07 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculations', '0002_savedcalculation_duty_exemption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedcalculation',
            name='is_explicitly_saved',
            field=models.BooleanField(default=False, help_text='True if the user explicitly saved this, False if it was auto-logged in history'),
        ),
    ]
