# Generated by Django 5.0.6 on 2026-07-01 18:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('exchange_rate', models.DecimalField(decimal_places=6, help_text='The conversion rate multiplier from base to target currency', max_digits=18)),
                ('source', models.CharField(blank=True, help_text='Source of the exchange rate data (e.g., RBZ)', max_length=100, null=True)),
                ('date', models.DateField(db_index=True, help_text='The date this exchange rate was published or applies to')),
                ('base_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_exchange_rates', to='core.currency')),
                ('target_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_exchange_rates', to='core.currency')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['base_currency', 'target_currency', '-date'], name='exchange_ra_base_cu_0214ea_idx')],
            },
        ),
    ]
