# Generated by Django 5.0.6 on 2026-07-01 18:19

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('iso_code', models.CharField(help_text='2-letter ISO 3166-1 alpha-2 country code (e.g. ZW)', max_length=2, unique=True, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.RegexValidator('^[A-Z]{2}$', 'ISO code must be 2 uppercase letters.')])),
                ('currency_code', models.CharField(blank=True, help_text='Default 3-letter currency code for this country', max_length=3, null=True, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.RegexValidator('^[A-Z]{3}$', 'Currency code must be 3 uppercase letters.')])),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(help_text='3-letter ISO currency code (e.g. USD)', max_length=3, unique=True, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.RegexValidator('^[A-Z]{3}$', 'Currency code must be 3 uppercase letters.')])),
                ('name', models.CharField(help_text='Full name of the currency', max_length=100)),
                ('symbol', models.CharField(help_text='Currency symbol (e.g. $)', max_length=10)),
                ('decimal_places', models.PositiveSmallIntegerField(default=2, help_text='Number of decimal places used')),
            ],
            options={
                'verbose_name_plural': 'Currencies',
                'ordering': ['code'],
            },
        ),
    ]
